#!/bin/bash
# Agent Skills MCP Integration (Auto-detect path)
# Generated by setup.sh v3.0

if [ -n "$BASH_SOURCE" ]; then
    _MCP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "$ZSH_VERSION" ]; then
    _MCP_SCRIPT_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
    _MCP_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

export AGENT_SKILLS_PATH="$_MCP_SCRIPT_DIR"

# Load helper functions
[ -f "$AGENT_SKILLS_PATH/mcp-skill-loader.sh" ] && source "$AGENT_SKILLS_PATH/mcp-skill-loader.sh"

# Skill query aliases
alias skill-list='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" list'
alias skill-match='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" match'
alias skill-query='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query'
alias skill-stats='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" stats'

# Token mode aliases
alias skill-query-toon='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode toon'
alias skill-query-compact='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode compact'
alias skill-query-full='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode full'

# MCP Agent functions (default: toon mode - 95% token savings)
gemini-skill() {
    local query="$1"
    local mode="${2:-toon}"
    python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query "$query" --tool gemini --mode "$mode" 2>/dev/null || echo "No matching skill for: $query"
}

codex-skill() {
    local query="$1"
    local mode="${2:-toon}"
    python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query "$query" --tool codex --mode "$mode" 2>/dev/null || echo "No matching skill for: $query"
}

# Check MCP environment status
mcp-status() {
    echo "🔍 MCP Environment Status"
    echo "========================="
    command -v claude &>/dev/null && echo "✅ Claude CLI: Installed" || echo "❌ Claude CLI: Not found"
    if command -v claude &>/dev/null; then
        claude mcp list 2>/dev/null | grep -E "(gemini-cli|codex-cli)" || echo "  No MCP servers registered"
    fi
}

export -f gemini-skill codex-skill mcp-status 2>/dev/null || true
unset _MCP_SCRIPT_DIR
