#!/bin/bash

# Agent Skills Setup Script
# Unified setup with token optimization, MCP integration, and Multi-Agent workflow

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Resolve script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_SKILLS_DIR="$SCRIPT_DIR"

# Skill categories
SKILL_CATEGORIES=(backend frontend code-quality infrastructure documentation project-management search-analysis utilities)

# ============================================================
# Helper Functions
# ============================================================

print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_header() { echo -e "${CYAN}━━━ $1 ━━━${NC}"; }

# Copy skills to destination
copy_skills() {
    local dest="$1"
    local verbose="$2"
    local copied=0

    for category in "${SKILL_CATEGORIES[@]}"; do
        if [ -d "$AGENT_SKILLS_DIR/$category" ]; then
            cp -r "$AGENT_SKILLS_DIR/$category" "$dest/"
            local count=$(find "$AGENT_SKILLS_DIR/$category" -name "SKILL.md" | wc -l | tr -d ' ')
            copied=$((copied + count))
            [ "$verbose" = "true" ] && print_success "  ✓ $category ($count skills)"
        fi
    done
    echo "$copied"
}

# Generate compact/toon skills
generate_compact_skills() {
    if [ -f "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" ]; then
        print_info "Generating token-optimized skills (compact/toon)..."
        python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" 2>/dev/null
        return 0
    else
        print_warning "generate_compact_skills.py not found"
        return 1
    fi
}

# Setup MCP shell config
setup_mcp_shell_config() {
    cat > "$AGENT_SKILLS_DIR/mcp-shell-config.sh" << 'EOFCONFIG'
#!/bin/bash
# Agent Skills MCP Integration (Auto-detect path)

if [ -n "$BASH_SOURCE" ]; then
    _MCP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "$ZSH_VERSION" ]; then
    _MCP_SCRIPT_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
    _MCP_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

export AGENT_SKILLS_PATH="$_MCP_SCRIPT_DIR"

# Load helper functions
[ -f "$AGENT_SKILLS_PATH/mcp-skill-loader.sh" ] && source "$AGENT_SKILLS_PATH/mcp-skill-loader.sh"

# Aliases
alias skill-list='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" list'
alias skill-match='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" match'
alias skill-query='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query'
alias skill-stats='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" stats'

# Token mode aliases
alias skill-query-toon='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode toon'
alias skill-query-compact='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode compact'
alias skill-query-full='python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query --mode full'

# MCP functions (default: toon mode for minimal tokens)
gemini-skill() {
    local query="$1"
    local mode="${2:-toon}"
    python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query "$query" --tool gemini --mode "$mode" 2>/dev/null || echo "No matching skill for: $query"
}

codex-skill() {
    local query="$1"
    local mode="${2:-toon}"
    python3 "$AGENT_SKILLS_PATH/skill-query-handler.py" query "$query" --tool codex --mode "$mode" 2>/dev/null || echo "No matching skill for: $query"
}

export -f gemini-skill codex-skill
unset _MCP_SCRIPT_DIR
EOFCONFIG
    chmod +x "$AGENT_SKILLS_DIR/mcp-shell-config.sh"
}

# Configure shell RC file
configure_shell_rc() {
    local auto_configure="$1"

    # Detect shell
    local SHELL_RC=""
    if [ "$SHELL" = "/bin/zsh" ] || [ "$SHELL" = "/usr/bin/zsh" ]; then
        SHELL_RC="$HOME/.zshrc"
    else
        SHELL_RC="$HOME/.bashrc"
    fi

    if [ "$auto_configure" = "auto" ]; then
        # Check if already configured
        local MARKER="# Agent Skills MCP Integration"
        if grep -q "$MARKER" "$SHELL_RC" 2>/dev/null; then
            # Remove old and add new
            sed -i.bak "/$MARKER/,/# End Agent Skills MCP/d" "$SHELL_RC" 2>/dev/null || \
            sed -i '' "/$MARKER/,/# End Agent Skills MCP/d" "$SHELL_RC" 2>/dev/null
        fi

        # Add new configuration
        {
            echo ""
            echo "$MARKER"
            echo "# Auto-generated by setup.sh - $(date +%Y-%m-%d)"
            echo "[ -f \"$AGENT_SKILLS_DIR/mcp-shell-config.sh\" ] && source \"$AGENT_SKILLS_DIR/mcp-shell-config.sh\""
            echo "# End Agent Skills MCP"
        } >> "$SHELL_RC"

        print_success "Shell RC configured: $SHELL_RC"
        return 0
    fi

    return 1
}

# Generate CLAUDE.md for multi-agent orchestration
generate_claude_md() {
    local project_dir="$(dirname "$AGENT_SKILLS_DIR")"
    cat > "$project_dir/CLAUDE.md" << 'EOFCLAUDEMD'
# Agent Skills - Multi-Agent Workflow

> 이 프로젝트는 Claude Code를 중심으로 Gemini-CLI와 Codex-CLI를 통합하는 Multi-Agent 시스템입니다.

## Agent Roles

| Agent | Role | MCP Tool | Best For |
|-------|------|----------|----------|
| **Claude Code** | Orchestrator | Built-in | 계획 수립, 코드 생성, 스킬 해석 |
| **Gemini-CLI** | Analyst | `ask-gemini` | 대용량 분석, 리서치, 코드 리뷰 |
| **Codex-CLI** | Executor | `shell` | 명령 실행, 빌드, 배포 |

## Multi-Agent Workflow

### When to Use Each Agent

**Claude Code (기본)**: 코드 작성/수정, 파일 읽기/쓰기, 스킬 기반 작업 계획

**Gemini-CLI (`ask-gemini`)**: 대용량 코드베이스 분석 (1M+ 토큰), 복잡한 아키텍처 리서치

**Codex-CLI (`shell`)**: 장시간 실행 명령, Docker/Kubernetes 작업, 빌드/배포

### Skill Integration

```bash
# 스킬 쿼리 (기본: toon 모드 - 95% 토큰 절감)
gemini-skill "API 설계해줘"
gemini-skill "query" compact  # 88% 절감
gemini-skill "query" full     # 상세
```

### Orchestration Examples

**API 설계 + 구현**:
1. [Claude] 스킬 로드 → API 스펙 설계
2. [Codex] shell "npm test"
3. [Claude] 결과 리포트

**대규모 코드 리뷰**:
1. [Gemini] ask-gemini "@src/ 전체 분석"
2. [Claude] 개선점 도출 및 수정

## Available Skills

- `backend/`: API 설계, DB 스키마, 인증
- `frontend/`: UI 컴포넌트, 상태 관리
- `code-quality/`: 코드 리뷰, 디버깅
- `infrastructure/`: 배포, 모니터링, 보안
- `documentation/`: 기술 문서, API 문서
- `utilities/`: Git, 환경 설정

## MCP Server Check

```bash
claude mcp list
# Expected: gemini-cli, codex-cli - Connected
```

---
**Version**: 2.3.0 | **Workflow**: Multi-Agent
EOFCLAUDEMD
    print_success "CLAUDE.md created for multi-agent orchestration"
}

# Configure MCP servers
configure_mcp_servers() {
    local auto_configure="$1"

    if [ "$auto_configure" = "auto" ]; then
        print_info "Configuring MCP servers..."

        # Check if claude CLI is available
        if ! command -v claude &> /dev/null; then
            print_warning "Claude CLI not found. Skipping MCP server configuration."
            print_info "Install Claude CLI first, then run: claude mcp add gemini-cli -s user -- npx -y gemini-mcp-tool"
            return 1
        fi

        # Add gemini-cli MCP server
        if claude mcp list 2>/dev/null | grep -q "gemini-cli"; then
            print_info "gemini-cli already configured"
        else
            print_info "Adding gemini-cli MCP server..."
            claude mcp add gemini-cli -s user -- npx -y gemini-mcp-tool 2>/dev/null || \
                print_warning "Failed to add gemini-cli (may need manual setup)"
        fi

        # Add codex-cli MCP server
        if claude mcp list 2>/dev/null | grep -q "codex-cli"; then
            print_info "codex-cli already configured"
        else
            print_info "Adding codex-cli MCP server..."
            claude mcp add codex-cli -s user -- npx -y @anthropic-ai/claude-code-mcp-codex 2>/dev/null || \
                print_warning "Failed to add codex-cli (may need manual setup)"
        fi

        print_success "MCP servers configured"
        return 0
    fi

    return 1
}

# ============================================================
# Main Menu
# ============================================================

echo ""
echo -e "${CYAN}🚀 Agent Skills Setup${NC}"
echo "====================="
echo ""
print_info "Directory: $AGENT_SKILLS_DIR"
echo ""

echo "Select setup option:"
echo ""
echo -e "  ${GREEN}1) Quick Setup (Recommended)${NC}"
echo "     → Multi-Agent workflow + Token optimization + MCP servers"
echo ""
echo "  2) Claude Code only"
echo "  3) ChatGPT (Knowledge zip)"
echo "  4) Gemini (Python API)"
echo "  5) Token Optimization only"
echo "  6) MCP Integration only"
echo "  7) Validate Skills"
echo "  8) Exit"
echo ""
read -p "Enter choice (1-8): " choice

case "$choice" in
    1)
        # ============================================================
        # Quick Setup - All-in-one
        # ============================================================
        echo ""
        print_header "Quick Setup - All-in-one Multi-Agent Configuration"
        echo ""

        TOTAL_STEPS=7
        CURRENT_STEP=0

        # Step 1: Token Optimization
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Generating token-optimized skills..."
        if command -v python3 &> /dev/null && [ -f "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" ]; then
            python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" 2>&1 | tail -5
            print_success "Token optimization complete (toon: 95% reduction)"
        else
            print_warning "Skipping token optimization (Python3 or script not found)"
        fi
        echo ""

        # Step 2: Claude Setup
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up Claude Code skills..."
        if git rev-parse --git-dir > /dev/null 2>&1; then
            mkdir -p "$(dirname "$AGENT_SKILLS_DIR")/.claude/skills"
            COPIED=$(copy_skills "$(dirname "$AGENT_SKILLS_DIR")/.claude/skills" "false")
            print_success "Claude project skills: $COPIED files copied"
        fi
        mkdir -p ~/.claude/skills
        PERSONAL=$(copy_skills "$HOME/.claude/skills" "false")
        print_success "Claude personal skills: $PERSONAL files copied"
        echo ""

        # Step 3: MCP Shell Config
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Creating MCP shell configuration..."
        setup_mcp_shell_config
        print_success "mcp-shell-config.sh created"
        echo ""

        # Step 4: Shell RC Configuration
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Configuring shell RC..."
        echo ""
        echo "Add MCP commands to your shell?"
        echo "  1) Yes, configure automatically (Recommended)"
        echo "  2) No, I'll do it manually"
        echo ""
        read -p "Choice (1-2): " shell_choice

        if [ "$shell_choice" = "1" ]; then
            configure_shell_rc "auto"
        else
            print_info "Manual setup: Add this to your ~/.zshrc or ~/.bashrc:"
            echo "  source \"$AGENT_SKILLS_DIR/mcp-shell-config.sh\""
        fi
        echo ""

        # Step 5: Multi-Agent Orchestration (CLAUDE.md)
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Creating multi-agent orchestration..."
        generate_claude_md
        echo ""

        # Step 6: MCP Servers Configuration
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] MCP servers configuration..."
        echo ""
        echo "Configure MCP servers for multi-agent workflow?"
        echo "  1) Yes, configure automatically (gemini-cli + codex-cli)"
        echo "  2) No, I'll do it manually"
        echo ""
        read -p "Choice (1-2): " mcp_choice

        if [ "$mcp_choice" = "1" ]; then
            configure_mcp_servers "auto"
        else
            print_info "Manual setup commands:"
            echo "  claude mcp add gemini-cli -s user -- npx -y gemini-mcp-tool"
            echo "  claude mcp add codex-cli -s user -- npx -y @anthropic-ai/claude-code-mcp-codex"
        fi
        echo ""

        # Step 7: Verification
        CURRENT_STEP=$((CURRENT_STEP + 1))
        print_info "[$CURRENT_STEP/$TOTAL_STEPS] Verifying setup..."

        # Check token stats
        if command -v python3 &> /dev/null; then
            TOON_COUNT=$(find "$AGENT_SKILLS_DIR" -name "SKILL.toon" | wc -l | tr -d ' ')
            COMPACT_COUNT=$(find "$AGENT_SKILLS_DIR" -name "SKILL.compact.md" | wc -l | tr -d ' ')
            print_success "Token files: $TOON_COUNT toon, $COMPACT_COUNT compact"
        fi

        # Test gemini-skill
        if bash -c "source \"$AGENT_SKILLS_DIR/mcp-shell-config.sh\" && type gemini-skill" &>/dev/null; then
            print_success "gemini-skill function: Ready"
        fi

        # Check CLAUDE.md
        if [ -f "$(dirname "$AGENT_SKILLS_DIR")/CLAUDE.md" ]; then
            print_success "CLAUDE.md: Ready (Multi-Agent Orchestration)"
        fi

        echo ""
        print_success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        print_success "Multi-Agent Setup Complete! 🎉"
        print_success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""

        print_info "📚 Next Steps:"
        echo ""
        echo "  1. Reload shell:"
        echo "     ${BLUE}source ~/.zshrc${NC}  # or ~/.bashrc"
        echo ""
        echo "  2. Verify MCP servers:"
        echo "     ${BLUE}claude mcp list${NC}"
        echo ""
        echo "  3. Test multi-agent workflow:"
        echo "     ${BLUE}gemini-skill \"API 설계해줘\"${NC}"
        echo ""
        echo "  4. Use with Claude Code (multi-agent auto-orchestration):"
        echo "     ${BLUE}\"REST API를 설계하고 테스트해줘\"${NC}"
        echo ""

        print_info "🤖 Multi-Agent Roles:"
        echo "  Claude Code  → Orchestrator (계획, 코드 생성)"
        echo "  Gemini-CLI   → Analyst (대용량 분석, 리서치)"
        echo "  Codex-CLI    → Executor (명령 실행, 배포)"
        echo ""

        print_info "🎯 Default Mode: toon (95% token reduction)"
        echo "  gemini-skill \"query\"           → toon mode"
        echo "  gemini-skill \"query\" compact   → compact mode"
        echo "  gemini-skill \"query\" full      → full detail"
        echo ""
        ;;

    2)
        # Claude Code only
        echo ""
        print_header "Claude Code Setup"
        echo ""

        # Generate compact skills first
        if command -v python3 &> /dev/null && [ -f "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" ]; then
            print_info "Generating token-optimized skills..."
            python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" 2>&1 | tail -3
            echo ""
        fi

        if git rev-parse --git-dir > /dev/null 2>&1; then
            print_info "Setting up project skills..."
            mkdir -p "$(dirname "$AGENT_SKILLS_DIR")/.claude/skills"
            COPIED=$(copy_skills "$(dirname "$AGENT_SKILLS_DIR")/.claude/skills" "true")
            print_success "Project skills: $COPIED files in .claude/skills/"
        fi

        echo ""
        read -p "Set up personal skills in ~/.claude/skills/? (y/n): " personal
        if [[ $personal =~ ^[Yy]$ ]]; then
            mkdir -p ~/.claude/skills
            PERSONAL=$(copy_skills "$HOME/.claude/skills" "true")
            print_success "Personal skills: $PERSONAL files"
        fi

        echo ""
        print_success "Claude Code setup complete!"
        echo ""
        echo "Next: Run ${BLUE}claude${NC} and ask ${BLUE}\"What skills are available?\"${NC}"
        ;;

    3)
        # ChatGPT
        echo ""
        print_header "ChatGPT Setup"
        echo ""

        ZIP_FILE="agent-skills-$(date +%Y%m%d).zip"
        TEMP_DIR="$(mktemp -d)"
        trap "rm -rf $TEMP_DIR" EXIT

        for cat in "${SKILL_CATEGORIES[@]}"; do
            [ -d "$AGENT_SKILLS_DIR/$cat" ] && cp -r "$AGENT_SKILLS_DIR/$cat" "$TEMP_DIR/"
        done

        (cd "$TEMP_DIR" && zip -r "$AGENT_SKILLS_DIR/$ZIP_FILE" . > /dev/null 2>&1)

        print_success "Created: $ZIP_FILE"
        echo ""
        echo "Upload to ChatGPT Custom GPT → Knowledge section"
        ;;

    4)
        # Gemini
        echo ""
        print_header "Gemini Setup"
        echo ""

        cat > "$(dirname "$AGENT_SKILLS_DIR")/GEMINI.md" << 'EOF'
# Agent Skills for Gemini

이 프로젝트는 Agent Skills 시스템을 사용합니다.
`.agent-skills/` 폴더의 스킬들을 작업 매뉴얼로 참조하세요.

## 스킬 카테고리
- backend/: API 설계, DB 스키마
- frontend/: UI 컴포넌트, 반응형 디자인
- code-quality/: 코드 리뷰, 디버깅
- infrastructure/: 배포, 모니터링
- documentation/: 기술 문서
- utilities/: Git, 환경 설정

## 사용법
1. 관련 SKILL.md 또는 SKILL.toon 파일 참조
2. 지시사항에 따라 작업 수행
3. 출력 포맷 준수
EOF

        print_success "GEMINI.md created"

        if command -v python3 &> /dev/null; then
            if ! python3 -c "import google.generativeai" 2>/dev/null; then
                read -p "Install google-generativeai? (y/n): " install
                [[ $install =~ ^[Yy]$ ]] && pip3 install google-generativeai
            fi
        fi
        ;;

    5)
        # Token Optimization only
        echo ""
        print_header "Token Optimization"
        echo ""

        if ! command -v python3 &> /dev/null; then
            print_warning "Python 3 required"
            exit 1
        fi

        echo "1) Generate all compact/toon files"
        echo "2) Show statistics"
        echo "3) Clean generated files"
        echo ""
        read -p "Choice (1-3): " opt

        case "$opt" in
            1)
                python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py"
                ;;
            2)
                python3 "$AGENT_SKILLS_DIR/skill-query-handler.py" stats
                ;;
            3)
                python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" --clean
                ;;
        esac
        ;;

    6)
        # MCP Integration only
        echo ""
        print_header "MCP Integration"
        echo ""

        # Generate compact skills
        if command -v python3 &> /dev/null && [ -f "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" ]; then
            print_info "Generating token-optimized skills..."
            python3 "$AGENT_SKILLS_DIR/scripts/generate_compact_skills.py" 2>&1 | tail -3
            echo ""
        fi

        print_info "Creating MCP configuration..."
        setup_mcp_shell_config
        print_success "mcp-shell-config.sh created"

        echo ""
        echo "Configure shell automatically?"
        echo "  1) Yes"
        echo "  2) No"
        read -p "Choice: " rc_choice

        if [ "$rc_choice" = "1" ]; then
            configure_shell_rc "auto"
        fi

        echo ""
        print_success "MCP Integration complete!"
        echo ""
        echo "Reload shell: ${BLUE}source ~/.zshrc${NC}"
        echo "Test: ${BLUE}gemini-skill \"API 설계\"${NC}"
        ;;

    7)
        # Validate
        echo ""
        print_header "Skill Validation"
        echo ""

        if [ -f "$AGENT_SKILLS_DIR/validate_claude_skills.py" ]; then
            python3 "$AGENT_SKILLS_DIR/validate_claude_skills.py"
        else
            SKILL_COUNT=$(find "$AGENT_SKILLS_DIR" -name "SKILL.md" | wc -l | tr -d ' ')
            TOON_COUNT=$(find "$AGENT_SKILLS_DIR" -name "SKILL.toon" | wc -l | tr -d ' ')
            echo "Skills found: $SKILL_COUNT SKILL.md, $TOON_COUNT SKILL.toon"
        fi
        ;;

    8)
        echo "Exiting..."
        exit 0
        ;;

    *)
        print_warning "Invalid choice"
        exit 1
        ;;
esac

echo ""
print_success "Setup complete! 🎉"
echo ""
