#!/usr/bin/env bash
# conductor-pr.sh — Conductor 에이전트 결과로 GitHub PR 생성
# 사용법: bash scripts/conductor-pr.sh <feature-name> [base-branch]
#
# 예시:
#   bash scripts/conductor-pr.sh user-dashboard main

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}ℹ️  $*${NC}"; }
ok()    { echo -e "${GREEN}✅ $*${NC}"; }
warn()  { echo -e "${YELLOW}⚠️  $*${NC}"; }
error() { echo -e "${RED}❌ $*${NC}" >&2; }

# ─── 인자 파싱 ───────────────────────────────────────────────────────────────
FEATURE_RAW="${1:-}"
BASE_BRANCH="${2:-main}"
SKIP_HOOKS="${CONDUCTOR_SKIP_HOOKS:-0}"
HOOKS_DIR="${CONDUCTOR_HOOKS_DIR:-$(git rev-parse --show-toplevel)/scripts/hooks}"

if [[ -z "$FEATURE_RAW" ]]; then
  error "사용법: $0 <feature-name> [base-branch]"
  exit 1
fi

FEATURE=$(echo "$FEATURE_RAW" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
ROOT_DIR="$(git rev-parse --show-toplevel)"
TREES_DIR="$ROOT_DIR/trees"

# gh CLI 확인
if ! command -v gh &>/dev/null; then
  error "gh CLI가 필요합니다. https://cli.github.com 에서 설치하세요."
  exit 1
fi

# gh 인증 확인
if ! gh auth status &>/dev/null; then
  error "gh CLI 인증이 필요합니다: gh auth login"
  exit 1
fi

# ─── 훅 실행 ─────────────────────────────────────────────────────────────────
run_hook() {
  local hook_name="$1"
  local hook_file="$HOOKS_DIR/${hook_name}.sh"
  if [[ "$SKIP_HOOKS" == "1" ]]; then return 0; fi
  if [[ -x "$hook_file" ]]; then
    info "훅 실행: $hook_name"
    bash "$hook_file" "$FEATURE" "$BASE_BRANCH" || return 1
  fi
  return 0
}

if ! run_hook "pre-pr"; then
  error "pre-pr 훅 실패. 중단합니다."
  exit 1
fi

# ─── worktree 스캔 및 PR 생성 ────────────────────────────────────────────────
echo ""
info "PR 생성 시작: feat/$FEATURE-*"
echo ""

CREATED_PRS=()

for tree_path in "$TREES_DIR"/feat-"$FEATURE"-*; do
  [[ -d "$tree_path" ]] || continue

  AGENT=$(basename "$tree_path" | sed "s/feat-$FEATURE-//")
  BRANCH="feat/$FEATURE-$AGENT"

  # 변경사항 확인
  cd "$tree_path"
  if [[ -z "$(git status --porcelain)" ]] && [[ "$(git log --oneline HEAD...origin/$BASE_BRANCH 2>/dev/null | wc -l)" -eq 0 ]]; then
    warn "$AGENT: 변경사항 없음. 건너뜁니다."
    cd "$ROOT_DIR"
    continue
  fi

  # 커밋 안된 변경사항 자동 커밋
  if [[ -n "$(git status --porcelain)" ]]; then
    info "$AGENT: 변경사항 커밋 중..."
    git add -A
    git commit -m "feat($FEATURE): $AGENT 에이전트 구현

Auto-committed by conductor-pr.sh
Agent: $AGENT
Feature: $FEATURE
Base: $BASE_BRANCH" || warn "$AGENT: 커밋 실패 (이미 커밋됨?)"
  fi

  # 브랜치 push
  info "$AGENT: 브랜치 push..."
  git push origin "$BRANCH" --force-with-lease 2>/dev/null || \
  git push origin "$BRANCH" 2>/dev/null || \
  warn "$AGENT: push 실패 (원격 권한 확인)"

  cd "$ROOT_DIR"

  # PR 생성
  info "$AGENT: PR 생성 중..."
  PR_BODY="## $FEATURE — $AGENT 에이전트 구현

이 PR은 \`conductor.sh\`에 의해 자동 생성되었습니다.

### 에이전트 정보
- **에이전트**: $AGENT
- **기능**: $FEATURE
- **베이스 브랜치**: $BASE_BRANCH
- **worktree 경로**: trees/feat-$FEATURE-$AGENT

### 비교 PR
$(for t in "$TREES_DIR"/feat-"$FEATURE"-*; do
  [[ -d "$t" ]] || continue
  a=$(basename "$t" | sed "s/feat-$FEATURE-//")
  [[ "$a" == "$AGENT" ]] && continue
  echo "- feat/$FEATURE-$a"
done)

### 리뷰 포인트
- [ ] 코드 품질 및 패턴
- [ ] 성능 및 최적화
- [ ] 테스트 커버리지
- [ ] 타입 안전성

> Generated by [Conductor Pattern](../docs/conductor-pattern/README.md)"

  PR_URL=$(gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH" \
    --title "feat($FEATURE): $AGENT 구현" \
    --body "$PR_BODY" \
    --draft \
    2>/dev/null) && {
    ok "$AGENT PR: $PR_URL"
    CREATED_PRS+=("$PR_URL")
  } || warn "$AGENT: PR 생성 실패 (이미 존재하거나 권한 부족)"
done

# ─── post-pr 훅 ──────────────────────────────────────────────────────────────
run_hook "post-pr" || warn "post-pr 훅 경고"

# ─── 결과 요약 ───────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════╗"
echo "║  PR 생성 완료                         ║"
echo "╚══════════════════════════════════════╝"
echo ""
if [[ ${#CREATED_PRS[@]} -gt 0 ]]; then
  echo "생성된 PR:"
  for pr in "${CREATED_PRS[@]}"; do
    echo "  🔗 $pr"
  done
  echo ""
  echo "리뷰 후 최적 구현을 선택하거나 cherry-pick으로 조합하세요."
else
  warn "생성된 PR이 없습니다. worktree에 변경사항이 있는지 확인하세요."
fi
